### ISSUE TITLE
Inquiry on some minor implementation details

### ISSUE THREAD

**Issue by galsang** [harvardnlp/compound-pcfg#1]
Hello, thanks for sharing your code, first of all, which is well-structured and easy to understand.
I have a few questions about the details of your implementation.

1. In your paper, you said 

> We employ a curriculum learning strategy (Bengio et al., 2009) where we train only on sentences of length up to 30 in the first epoch, and increase this length limit by 1 each epoch.

But in the code, I found that the maximum of the lengths of sentences increases as
30 -> 40 -> 41 -> ... even though I expected this should change like 30 -> 31 -> 32 -> ... 
Maybe this undesirable? working seems coming from the below line in train.py.

https://github.com/harvardnlp/compound-pcfg/blob/43359b8679061523c3c7f841705cbac9584e474e/train.py#L130

Is there any reason you used **max** instead of **min**?
It seems right to change the max function into the min function on the basis of your paper.

2. And, I'm just curious about why we should consider the EOS token ('\</s\>') in this model by explicitly adding 1 to the number of words in a sentence as below.

https://github.com/harvardnlp/compound-pcfg/blob/43359b8679061523c3c7f841705cbac9584e474e/train.py#L105

Thanks again for opening your code!

**Comment by yoonkim** [comment]
Thanks for catching this! I fixed it.

Regarding (2), the reason is that for PPL, the LSTM language model (and PRPN/ON) does count the `</s>` token (since we train on a version of PTB with punctuation stripped out). For the PCFG models, we do not explicitly need to generate `</s>` because it is implied when there are no more terminals to generate. To put it another way, generating from a PCFG  would involve generating the sentence and then deterministcally adding  `</s>` to generated sentence. Since the final `</s>` is deterministic, we do not incur a loss for it.

Hope this clarifies things!

**Comment by galsang** [comment]
I appreciate for your quick reply, and everything looks clear. Thanks!
